### ISSUE TITLE
Add phpMyAdmin

### ISSUE THREAD

**Issue by vbezruchkin** [intelliants/docker-subrion#1]
Add phpMyAdmin to image please.

**Comment by nkanaev** [comment]
phpMyAdmin support can be added separately by running a command:

``` console
$ docker run --name some-phpmyadmin --link some-mysql:db -p 8081:80 -d phpmyadmin/phpmyadmin
```

This operation will create a new container, which is accessible when you visit `http://localhost:8081` or `http://host-ip:8081`
